### ISSUE TITLE
Cheese Game

### ISSUE THREAD

**Issue by Hartrik** [MecanixCreations/Mecanix-Sand-Game-JS-Edits#1]
Hi!
I like the Cheese Game. I would publish it alongside my scenarios, but there’s a catch.

I found that it is built on top of version 23w41a which is quite old. Unfortunately, it is not API compatible and it is also using an old Bootstrap version which is not compatible with the version used by SandSaga.com.

The ultimate solution would be if you would be willing to remake it into a scenario with latest Sand Game JS engine version.
By following guidelines at https://sandsaga.com/manual and using https://github.com/Hartrik/sand-saga-scenario
In the scenario, you only define tools, templates, and scenes and it works. You can’t change everything (through I'm continuously adding more options), but it has other advantages - for example, it would work with future versions.

What do you think?

---
There is how it could look like...

![preview](https://github.com/MecanixCreations/Mecanix-Sand-Game-JS-Edits/assets/6131815/6d8bcad8-e157-4d84-b88f-6df26ee6e95e)

**Comment by MecanixCreations** [comment]
I can try to put all of cheese game into a sand saga scenario section, and make individual ones for each scene, or I will first try to update the API to v12 api

**Comment by MecanixCreations** [comment]
the only issue with cheese game is the brushes sometimes use the old image to brush tool component

![Screenshot 2024-04-08 8 40 28 AM](https://github.com/MecanixCreations/Mecanix-Sand-Game-JS-Edits/assets/148281271/2fa23f81-339b-46fb-a9e3-e63d76cf9df4)

**Comment by MecanixCreations** [comment]
progress!
![image](https://github.com/MecanixCreations/Mecanix-Sand-Game-JS-Edits/assets/148281271/e73fefd6-17b0-45e5-a7de-f3f64a5c3372)

**Comment by Hartrik** [comment]
Glad to hear that! If any problems arise, I'll be happy to help. But I didn't quite get the problem with the images :)

**Comment by MecanixCreations** [comment]
I found the `s.colorTexture` property and finally after an hour of work :
![image](https://github.com/MecanixCreations/Mecanix-Sand-Game-JS-Edits/assets/148281271/be67726f-aec4-4887-90a2-74c928e5b3b4)

finally!

**Comment by MecanixCreations** [comment]
I keep forgetting to join the discord, so I will see you there, my username  is GE0PLEX

**Comment by MecanixCreations** [comment]
btw i think this will be a great addition to sand saga

**Comment by MecanixCreations** [comment]
the first version  is done other than templates :0
so if you can, try to add it to sand saga!

**Comment by Hartrik** [comment]
I will reply on Discord

https://discord.gg/j8G37wFX32

**Comment by MecanixCreations** [comment]
cheese game is 100% ready for sand saga
